server:
  port: 8000
zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8080/multiplications
    results:
      path: /results/**
      url: http://localhost:8080/results
    leaders:
      path: /leaders/**
      url: http://localhost:8080/leaders
    stats:
      path: /stats/**
      url: http://localhost:8080/stats

#endpoints:
#  routes:
#    sensitive: false
#  trace:
#    sensitive: false

ribbon:
  eureka:
    enabled: false